FROM mcr.microsoft.com/devcontainers/base:bookworm

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    ca-certificates \
    python3 \
    python3-pip \
    ripgrep \
 && rm -rf /var/lib/apt/lists/*
